### PR TITLE
fix(webapp): header logo

### LINKED ISSUE #962: homepage logo and social media preview image
some images were broken and new suggestions by edwin were given

### PR DESCRIPTION
**Pull request by fvives99**
### What does this PR do?

- Resolve #962 

### Steps to test

1. See header logo
image

### CODE REVIEW

File: webapp/src/components/Header/index.js [hunk 1]
```diff
@@ -35,7 +35,7 @@ const HeaderLogo = () => {
       <Link href="https://eosio.online/">
```
Comment (xavier506) [inline webapp/src/components/Header/index.js:35]: <Link href="https://antelope.tools/">

**Review by xavier506 — APPROVED** [review]
LGTM
